# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[mgr]
cwd = { fg = "#89ddff" }

# Hovered
hovered         = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#fffac2", bold = true, italic = true, underline = true }
find_position = { fg = "#506477", bg = "reset", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#a6e3a1", bg = "#a6e3a1" }
marker_cut      = { fg = "#d0679d", bg = "#d0679d" }
marker_marked   = { fg = "#89ddff", bg = "#89ddff" }
marker_selected = { fg = "#fffac2", bg = "#fffac2" }

# Tab
tab_active   = { reversed = true }
tab_inactive = {}
tab_width    = 1

# Count
count_copied   = { fg = "#1e1e2e", bg = "#a6e3a1" }
count_cut      = { fg = "#1e1e2e", bg = "#d0679d" }
count_selected = { fg = "#1e1e2e", bg = "#fffac2" }

# Border
border_symbol = "│"
border_style  = { fg = "#7f849c" }

# : }}}


# : Tabs {{{

[tabs]
active   = { fg = "#1e1e2e", bg = "#5de4c7", bold = true }
inactive = { fg = "#5de4c7", bg = "#1e1e2e" }

# : }}}


# : Mode {{{

[mode]

normal_main = { fg = "#1e1e2e", bg = "#5de4c7", bold = true }
normal_alt  = { fg = "#5de4c7", bg = "#1e1e2e" }

# Select mode
select_main = { fg = "#1c1e28", bg = "#89ddff", bold = true }
select_alt  = { fg = "#89ddff", bg = "#1c1e28" }

# Unset mode
unset_main = { fg = "#1e1e2e", bg = "#f2cdcd", bold = true }
unset_alt  = { fg = "#f2cdcd", bg = "#1c1e28" }

# : }}}


# : Status bar {{{

[status]
# Permissions
perm_sep   = { fg = "#7f849c" }
perm_type  = { fg = "#5de4c7" }
perm_read  = { fg = "#fffac2" }
perm_write = { fg = "#d0679d" }
perm_exec  = { fg = "#a6e3a1" }

# Progress
progress_label  = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#5de4c7", bg = "#1e1e2e" }
progress_error  = { fg = "#d0679d", bg = "#1e1e2e" }

# : }}}


# : Pick {{{

[pick]
border   = { fg = "#5de4c7" }
active   = { fg = "#506477", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "#5de4c7" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[cmp]
border = { fg = "#5de4c7" }

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#5de4c7" }
title   = {}
hovered = { fg = "#506477", underline = true }

# : }}}


# : Which {{{

[which]
mask            = { bg = "#303341" }
cand            = { fg = "#89ddff" }
rest            = { fg = "#9399b2" }
desc            = { fg = "#506477" }
separator       = "  "
separator_style = { fg = "#585b70" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#89ddff" }
run     = { fg = "#506477" }
hovered = { reversed = true, bold = true }
footer  = { fg = "#303341", bg = "#add7ff" }

# : }}}


# : Notify {{{

[notify]
title_info  = { fg = "#a6e3a1" }
title_warn  = { fg = "#fffac2" }
title_error = { fg = "#d0679d" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#89ddff" },

	# Media
	{ mime = "{audio,video}/*", fg = "#fffac2" },

	# Archives
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#506477" },

	# Documents
	{ mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

	# Fallback
	{ name = "*", fg = "#add7ff" },
	{ name = "*/", fg = "#5de4c7" }
]

# : }}}
